import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body
        style={{
          fontFamily: "sans-serif",
          margin: 0,
          background: "#f8fafc",
          color: "#111",
        }}
      >
        {/* ナビゲーションバー */}
        <nav
          style={{
            display: "flex",
            gap: "1rem",
            alignItems: "center",
            padding: "0.75rem 1rem",
            background: "#1e3a8a",
            color: "#fff",
          }}
        >
          <a
            href="/"
            style={{ color: "#fff", textDecoration: "none", fontWeight: 600 }}
          >
            Home
          </a>
          <a
            href="/products"
            style={{ color: "#fff", textDecoration: "none" }}
          >
            商品一覧
          </a>
          <a
            href="/products/new"
            style={{ color: "#fff", textDecoration: "none" }}
          >
            商品追加
          </a>
        </nav>

        {/* ページ本体 */}
        <div style={{ maxWidth: 960, margin: "0 auto" }}>{children}</div>
      </body>
    </html>
  );
}
